# Generated by Django 5.0.14 on 2026-05-13 21:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medico", "0001_initial"),
        ("triage", "0003_remove_triaje_estado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="colaestado",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="colaestado",
            name="nombre",
        ),
        migrations.AddField(
            model_name="colaestado",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="colaestado",
            name="estado",
            field=models.CharField(
                choices=[
                    ("EN_ESPERA", "En espera"),
                    ("EN_CONSULTORIO", "En consultorio"),
                    ("FINALIZADO", "Finalizado"),
                ],
                default="EN_ESPERA",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="colaestado",
            name="triaje",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cola_estado",
                to="triage.triaje",
            ),
        ),
        migrations.AddField(
            model_name="colaestado",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
