# Generated by Django 5.0.14 on 2026-05-13 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medico", "0002_remove_colaestado_descripcion_and_more"),
        ("triage", "0003_remove_triaje_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colaestado",
            name="triaje",
            field=models.OneToOneField(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cola_estado",
                to="triage.triaje",
            ),
            preserve_default=False,
        ),
    ]
