# Generated by Django 5.0.14 on 2026-06-23 20:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("admision", "0002_paciente_tipo_documento_alter_paciente_dni"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIChatUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(default=django.utils.timezone.localdate)),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage",
                        to="admision.paciente",
                    ),
                ),
            ],
            options={
                "unique_together": {("paciente", "fecha")},
            },
        ),
    ]
