# Generated by Django 5.0.14 on 2026-04-21 23:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroTriage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('presion_arterial', models.CharField(help_text='Ej: 120/80', max_length=7)),
                ('frecuencia_cardiaca', models.IntegerField(help_text='LPM')),
                ('temperatura', models.DecimalField(decimal_places=1, help_text='°C', max_digits=4)),
                ('saturacion_oxigeno', models.IntegerField(help_text='%')),
                ('motivo_consulta', models.TextField()),
                ('notas_medico', models.TextField(blank=True, help_text='Aquí el motor NLP extraerá el código CIE-10', null=True)),
                ('nivel_asignado', models.CharField(choices=[('1', 'Nivel 1 - Resucitación (Inmediata)'), ('2', 'Nivel 2 - Emergencia (10-15 min)'), ('3', 'Nivel 3 - Urgencia (60 min)'), ('4', 'Nivel 4 - Urgencia Menor (2 hrs)'), ('5', 'Nivel 5 - Sin Urgencia (4 hrs)')], default='3', max_length=1)),
                ('codigo_cie10_sugerido', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('procesado_por_ia', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triages', to='triage.paciente')),
            ],
        ),
    ]
