# Generated by Django 5.0.14 on 2026-05-13 20:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("admision", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Triaje",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "spo2",
                    models.PositiveSmallIntegerField(
                        help_text="Saturacion de oxigeno (%)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="SpO2",
                    ),
                ),
                (
                    "frecuencia_cardiaca",
                    models.PositiveSmallIntegerField(
                        help_text="Latidos por minuto",
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(250),
                        ],
                        verbose_name="Frecuencia cardiaca",
                    ),
                ),
                (
                    "temperatura",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Temperatura corporal en Celsius",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(45),
                        ],
                        verbose_name="Temperatura",
                    ),
                ),
                (
                    "red_flag",
                    models.CharField(
                        choices=[
                            ("NONE", "Sin bandera roja"),
                            ("DOLOR_TORACICO", "Dolor toracico"),
                            ("DIFICULTAD_RESPIRATORIA", "Dificultad respiratoria"),
                            ("HEMORRAGIA_ACTIVA", "Hemorragia activa"),
                        ],
                        default="NONE",
                        max_length=64,
                        verbose_name="Sintoma bandera roja",
                    ),
                ),
                (
                    "nivel_prioridad",
                    models.SmallIntegerField(
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Nivel de prioridad",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones clinicas"),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="triajes",
                        to="admision.paciente",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "usuario_enfermeria",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triajes_registrados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Triaje",
                "verbose_name_plural": "Triajes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["paciente", "-created_at"],
                        name="triage_tria_pacient_1301fe_idx",
                    ),
                    models.Index(
                        fields=["nivel_prioridad", "-created_at"],
                        name="triage_tria_nivel_p_adfb32_idx",
                    ),
                ],
            },
        ),
    ]
