# Generated by Django 5.0.14 on 2026-05-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("triage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="triaje",
            name="estado",
            field=models.CharField(
                choices=[
                    ("EN_ESPERA", "En espera"),
                    ("ATENDIDO", "Atendido"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="EN_ESPERA",
                max_length=20,
                verbose_name="Estado del triaje",
            ),
        ),
    ]
