# Generated by Django 5.0.14 on 2026-05-13 21:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("triage", "0002_triaje_estado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="triaje",
            name="estado",
        ),
    ]
