# Generated by Django 5.0.14 on 2026-05-29 01:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admision", "0001_initial"),
        ("triage", "0003_remove_triaje_estado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalTriaje",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "spo2",
                    models.PositiveSmallIntegerField(
                        help_text="Saturacion de oxigeno (%)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="SpO2",
                    ),
                ),
                (
                    "frecuencia_cardiaca",
                    models.PositiveSmallIntegerField(
                        help_text="Latidos por minuto",
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(250),
                        ],
                        verbose_name="Frecuencia cardiaca",
                    ),
                ),
                (
                    "temperatura",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Temperatura corporal en Celsius",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(45),
                        ],
                        verbose_name="Temperatura",
                    ),
                ),
                (
                    "red_flag",
                    models.CharField(
                        choices=[
                            ("NONE", "Sin bandera roja"),
                            ("DOLOR_TORACICO", "Dolor toracico"),
                            ("DIFICULTAD_RESPIRATORIA", "Dificultad respiratoria"),
                            ("HEMORRAGIA_ACTIVA", "Hemorragia activa"),
                        ],
                        default="NONE",
                        max_length=64,
                        verbose_name="Sintoma bandera roja",
                    ),
                ),
                (
                    "nivel_prioridad",
                    models.SmallIntegerField(
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Nivel de prioridad",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones clinicas"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="admision.paciente",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "usuario_enfermeria",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Triaje",
                "verbose_name_plural": "historical Triajes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
