# Generated by Django 5.0.14 on 2026-06-07 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("triage", "0004_historicaltriaje"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltriaje",
            name="presion_diastolica",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="mmHg (opcional)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(20),
                    django.core.validators.MaxValueValidator(200),
                ],
                verbose_name="Presion arterial diastolica",
            ),
        ),
        migrations.AddField(
            model_name="historicaltriaje",
            name="presion_sistolica",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="mmHg (opcional)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(40),
                    django.core.validators.MaxValueValidator(300),
                ],
                verbose_name="Presion arterial sistolica",
            ),
        ),
        migrations.AddField(
            model_name="triaje",
            name="presion_diastolica",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="mmHg (opcional)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(20),
                    django.core.validators.MaxValueValidator(200),
                ],
                verbose_name="Presion arterial diastolica",
            ),
        ),
        migrations.AddField(
            model_name="triaje",
            name="presion_sistolica",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="mmHg (opcional)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(40),
                    django.core.validators.MaxValueValidator(300),
                ],
                verbose_name="Presion arterial sistolica",
            ),
        ),
    ]
