# Generated by Django on 2026-05-14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("admision", "0001_initial"),
        ("triage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotaMedica",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("motivo_consulta", models.CharField(blank=True, max_length=255, verbose_name="Motivo de consulta")),
                ("contenido", models.TextField(verbose_name="Contenido clínico")),
                ("is_privada", models.BooleanField(default=False, verbose_name="Privada")),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notas_medicas",
                        to="admision.paciente",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "triaje",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notas_medicas",
                        to="triage.triaje",
                        verbose_name="Triaje relacionado",
                    ),
                ),
                (
                    "medico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notas_creadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Medico responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota médica",
                "verbose_name_plural": "Notas médicas",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["paciente", "-created_at"], name="consulta_not_paciente_idx")],
            },
        ),
    ]

