# Generated by Django 5.0.14 on 2026-05-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consulta", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notamedica",
            new_name="consulta_no_pacient_b8731f_idx",
            old_name="consulta_not_paciente_idx",
        ),
        migrations.AddField(
            model_name="notamedica",
            name="cie_accepted",
            field=models.BooleanField(
                default=False,
                help_text="Indica si la sugerencia CIE-10 fue aceptada por el médico",
                verbose_name="CIE-10 aceptado",
            ),
        ),
        migrations.AddField(
            model_name="notamedica",
            name="cie_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Código CIE-10 seleccionado (ej: A00, B20, etc.)",
                max_length=8,
                null=True,
                verbose_name="Código CIE-10",
            ),
        ),
        migrations.AddField(
            model_name="notamedica",
            name="cie_short_description",
            field=models.CharField(
                blank=True,
                help_text="Descripción corta del código CIE-10 seleccionado",
                max_length=255,
                null=True,
                verbose_name="Descripción CIE-10",
            ),
        ),
    ]
