# Generated by Django 5.0.14 on 2026-05-29 01:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "consulta",
            "0002_rename_consulta_not_paciente_idx_consulta_no_pacient_b8731f_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "presentacion",
                    models.CharField(max_length=100, verbose_name="Presentación"),
                ),
                (
                    "concentracion",
                    models.CharField(max_length=50, verbose_name="Concentración"),
                ),
            ],
            options={
                "verbose_name": "Medicamento",
                "verbose_name_plural": "Medicamentos",
            },
        ),
        migrations.AddField(
            model_name="notamedica",
            name="receta_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="ID de Receta",
            ),
        ),
        migrations.CreateModel(
            name="Prescripcion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dosis", models.CharField(max_length=100, verbose_name="Dosis")),
                (
                    "frecuencia",
                    models.CharField(max_length=100, verbose_name="Frecuencia"),
                ),
                ("duracion", models.CharField(max_length=100, verbose_name="Duración")),
                (
                    "instrucciones_adicionales",
                    models.TextField(
                        blank=True, null=True, verbose_name="Instrucciones adicionales"
                    ),
                ),
                (
                    "medicamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="consulta.medicamento",
                        verbose_name="Medicamento",
                    ),
                ),
                (
                    "nota_medica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescripciones",
                        to="consulta.notamedica",
                        verbose_name="Nota médica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescripción",
                "verbose_name_plural": "Prescripciones",
            },
        ),
    ]
