# Generated by Django 5.0.14 on 2026-06-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consulta", "0003_medicamento_notamedica_receta_id_prescripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="notamedica",
            name="cie_suggestions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de sugerencias propuestas por el motor de IA (no confirmadas)",
                verbose_name="Sugerencias CIE-10 (IA)",
            ),
        ),
        migrations.AddField(
            model_name="notamedica",
            name="estado_ia",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("PROCESANDO", "Procesando"),
                    ("LISTO", "Listo"),
                    ("ERROR", "Error"),
                ],
                db_index=True,
                default="PENDIENTE",
                help_text="Estado del análisis NLP en segundo plano",
                max_length=10,
                verbose_name="Estado de procesamiento IA",
            ),
        ),
    ]
