# Generated by Django 5.0.14 on 2026-06-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consulta", "0004_notamedica_cie_suggestions_notamedica_estado_ia"),
    ]

    operations = [
        migrations.AddField(
            model_name="notamedica",
            name="recomendacion_paciente",
            field=models.TextField(
                blank=True,
                help_text="Indicaciones que el paciente verá en su portal (no es la nota clínica).",
                verbose_name="Recomendación para el paciente",
            ),
        ),
    ]
