# Generated by Django 5.0.6 on 2024-07-15 21:30

from django.db import migrations


def ensure_default_permissions(schema_editor):
    """Force-create default model permissions during a data migration.

    Django creates default permissions via a ``post_migrate`` signal that runs
    *after* all migrations finish. On a fresh database (tests or a first deploy)
    the permissions do not exist yet while this data migration runs, so any group
    created here would end up empty. Creating them eagerly keeps the role
    assignments below working on any database.
    """
    from django.apps import apps as global_apps
    from django.contrib.auth.management import create_permissions

    for app_config in global_apps.get_app_configs():
        app_config.models_module = True
        try:
            create_permissions(
                app_config, verbosity=0, using=schema_editor.connection.alias
            )
        finally:
            app_config.models_module = None


def create_groups(apps, schema_editor):
    ensure_default_permissions(schema_editor)

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    # Definir los grupos y sus modelos asociados
    # El formato es: "NombreDelGrupo": ["app_label.model_name", ...]
    GROUPS_MODELS = {
        "Admision": ["admision.paciente"],
        "Enfermeros": ["triage.triaje", "triage.historicaltriaje"],
        "Medicos": [
            "consulta.notamedica",
            "consulta.prescripcion",
            "consulta.medicamento",
        ],
    }

    for group_name, models in GROUPS_MODELS.items():
        group, created = Group.objects.get_or_create(name=group_name)
        if created:
            print(f"Grupo '{group_name}' creado.")

        permissions_to_assign = []
        for model_str in models:
            app_label, model_name = model_str.split(".")
            try:
                content_type = ContentType.objects.get(
                    app_label=app_label, model=model_name
                )
                model_permissions = Permission.objects.filter(
                    content_type=content_type
                )
                permissions_to_assign.extend(model_permissions)
            except ContentType.DoesNotExist:
                print(
                    f"WARN: ContentType para {app_label}.{model_name} no encontrado. Omitiendo permisos."
                )

        if permissions_to_assign:
            group.permissions.set(permissions_to_assign)
            print(f"Permisos asignados al grupo '{group_name}'.")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        # Add dependencies to the latest migration of each app whose models are used.
        ("admision", "0001_initial"),
        ("triage", "0001_initial"),
        ("consulta", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]