# Generated by Django

from django.db import migrations


def ensure_default_permissions(schema_editor):
    """Force-create default model permissions during a data migration.

    See ``0002_create_groups`` for the rationale: permissions are normally
    created by a ``post_migrate`` signal that runs after this migration.
    """
    from django.apps import apps as global_apps
    from django.contrib.auth.management import create_permissions

    for app_config in global_apps.get_app_configs():
        app_config.models_module = True
        try:
            create_permissions(
                app_config, verbosity=0, using=schema_editor.connection.alias
            )
        finally:
            app_config.models_module = None


def update_groups(apps, schema_editor):
    ensure_default_permissions(schema_editor)

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    # --- 1. Arreglar permisos para el grupo Médicos ---
    try:
        medicos_group = Group.objects.get(name="Medicos")

        # Añadir permiso para ver y cambiar la cola de estado
        content_type = ContentType.objects.get(app_label="medico", model="colaestado")
        cola_permissions = Permission.objects.filter(content_type=content_type)

        current_permissions = list(medicos_group.permissions.all())
        for perm in cola_permissions:
            if perm not in current_permissions:
                current_permissions.append(perm)

        medicos_group.permissions.set(current_permissions)
        print("Permisos de 'colaestado' añadidos al grupo 'Medicos'.")

    except Group.DoesNotExist:
        print("WARN: Grupo 'Medicos' no encontrado, se omitió la actualización de permisos.")
    except ContentType.DoesNotExist:
        print("WARN: ContentType para 'medico.colaestado' no encontrado, se omitió la actualización.")


    # --- 2. Crear y asignar permisos para el nuevo grupo Pacientes ---
    pacientes_group, created = Group.objects.get_or_create(name="Pacientes")
    if created:
        print("Grupo 'Pacientes' creado.")

    try:
        # Darle permiso para VER (y solo ver) las notas médicas
        content_type = ContentType.objects.get(app_label="consulta", model="notamedica")
        view_nota_perm = Permission.objects.get(
            content_type=content_type, codename="view_notamedica"
        )
        
        pacientes_group.permissions.set([view_nota_perm])
        print("Permiso 'view_notamedica' asignado al grupo 'Pacientes'.")

    except ContentType.DoesNotExist:
        print("WARN: ContentType para 'consulta.notamedica' no encontrado, se omitió la asignación.")
    except Permission.DoesNotExist:
        print("WARN: Permiso 'view_notamedica' no encontrado, se omitió la asignación.")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_create_groups"),
        ("medico", "0001_initial"),
        ("consulta", "0001_initial"), # Dependencia correcta
    ]

    operations = [
        migrations.RunPython(update_groups),
    ]
