# Generated by Django 5.0.14 on 2026-05-11 06:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dni",
                    models.CharField(
                        db_index=True,
                        help_text="Documento nacional de identidad del paciente",
                        max_length=20,
                        unique=True,
                        verbose_name="DNI/Documento de Identidad",
                    ),
                ),
                ("nombres", models.CharField(max_length=150, verbose_name="Nombres")),
                (
                    "apellidos",
                    models.CharField(max_length=150, verbose_name="Apellidos"),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(verbose_name="Fecha de Nacimiento"),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        max_length=1,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True,
                        help_text="Número de contacto del paciente",
                        max_length=20,
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Correo electrónico del paciente",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "direccion",
                    models.TextField(
                        blank=True,
                        help_text="Dirección de residencia del paciente",
                        verbose_name="Dirección",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("activo", "Activo"), ("inactivo", "Inactivo")],
                        db_index=True,
                        default="activo",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pacientes_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario Creador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["dni", "-created_at"], name="admision_pa_dni_07019a_idx"
                    ),
                    models.Index(
                        fields=["estado", "-created_at"],
                        name="admision_pa_estado_97d57e_idx",
                    ),
                ],
            },
        ),
    ]
