# Generated by Django 5.0.14 on 2026-05-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admision", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("DNI", "DNI"),
                    ("PAS", "Pasaporte"),
                    ("CE", "Carné de Extranjería"),
                ],
                default="DNI",
                max_length=3,
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="dni",
            field=models.CharField(
                db_index=True,
                help_text="DNI, Pasaporte o Carné de Extranjería",
                max_length=20,
                unique=True,
                verbose_name="Número de Documento",
            ),
        ),
    ]
